object frmMian: TfrmMian
  Left = 465
  Top = 173
  BorderIcons = []
  BorderStyle = bsNone
  Caption = #24322#24120#25104#21697#26631#31614#25171#21360' - '#36873#25321#21151#33021
  ClientHeight = 394
  ClientWidth = 533
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 16
  object RzPanel4: TRzPanel
    Left = 0
    Top = 0
    Width = 533
    Height = 394
    Align = alClient
    Alignment = taLeftJustify
    BorderOuter = fsNone
    BorderColor = clRed
    BorderHighlight = clWhite
    BorderShadow = clWhite
    BorderWidth = 11
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 0
    object Label1: TLabel
      Left = 11
      Top = 11
      Width = 511
      Height = 56
      Align = alTop
      Alignment = taCenter
      AutoSize = False
      Caption = #36873#25321#21151#33021
      Color = clRed
      Font.Charset = GB2312_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
    end
    object Label4: TLabel
      Left = 142
      Top = 304
      Width = 249
      Height = 54
      Cursor = crHandPoint
      Alignment = taCenter
      AutoSize = False
      Caption = #21462#28040
      Color = clBlack
      Font.Charset = GB2312_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
      OnClick = Label4Click
      OnMouseMove = Label4MouseMove
      OnMouseLeave = Label4MouseLeave
    end
    object RzPanel1: TRzPanel
      Left = 11
      Top = 67
      Width = 511
      Height = 206
      Align = alTop
      Alignment = taLeftJustify
      BorderOuter = fsNone
      BorderColor = clMoneyGreen
      BorderHighlight = clWhite
      BorderShadow = clWhite
      BorderWidth = 1
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 0
      object Label2: TLabel
        Left = 82
        Top = 31
        Width = 123
        Height = 88
        Cursor = crHandPoint
        Alignment = taCenter
        AutoSize = False
        Caption = #20837#24211#21069
        Color = clLime
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Transparent = False
        Layout = tlCenter
        OnClick = Label2Click
        OnMouseMove = Label2MouseMove
        OnMouseLeave = Label2MouseLeave
      end
      object Label3: TLabel
        Left = 306
        Top = 31
        Width = 123
        Height = 88
        Cursor = crHandPoint
        Alignment = taCenter
        AutoSize = False
        Caption = #20837#24211#21518
        Color = clYellow
        Font.Charset = GB2312_CHARSET
        Font.Color = clMaroon
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Transparent = False
        Layout = tlCenter
        OnClick = Label3Click
        OnMouseMove = Label3MouseMove
        OnMouseLeave = Label3MouseLeave
      end
      object Label5: TLabel
        Left = -4
        Top = 149
        Width = 213
        Height = 41
        Alignment = taCenter
        AutoSize = False
        Caption = #27880#24847#65306#21407#26631#31614#38656#20808#20316#24223
        Color = clRed
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Transparent = False
        Layout = tlCenter
      end
    end
  end
  object ClientDataSet1: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'DS_getdata'
    RemoteServer = FDM.SC
    Left = 370
    Top = 21
  end
  object Timer1: TTimer
    Interval = 100
    OnTimer = Timer1Timer
    Left = 43
    Top = 83
  end
  object Timer2: TTimer
    OnTimer = Timer2Timer
    Left = 43
    Top = 139
  end
end
