object F_main: TF_main
  Left = 594
  Top = 309
  BorderStyle = bsNone
  Caption = 'F_main'
  ClientHeight = 72
  ClientWidth = 143
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = #23435#20307
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 16
  object RzPanel10: TRzPanel
    Left = 0
    Top = 0
    Width = 143
    Height = 72
    Align = alClient
    Alignment = taLeftJustify
    BorderOuter = fsNone
    BorderColor = 16776176
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Color = clWhite
    Ctl3D = True
    FlatColor = clTeal
    FlatColorAdjustment = 100
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentFont = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 0
    ThemeAware = False
    object Label99: TLabel
      Left = 568
      Top = 310
      Width = 16
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Color = clWhite
      Font.Charset = ANSI_CHARSET
      Font.Color = clTeal
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
      Layout = tlCenter
    end
    object Label5: TLabel
      Left = 0
      Top = 0
      Width = 143
      Height = 30
      Align = alTop
      Alignment = taCenter
      AutoSize = False
      Caption = #21147#30495#36861#28335#31649#29702#31995#32479
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clGreen
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
    end
    object Label1: TLabel
      Left = 96
      Top = 30
      Width = 47
      Height = 42
      Align = alClient
      Alignment = taCenter
      AutoSize = False
      Caption = '59'
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
    end
    object Label2: TLabel
      Left = 0
      Top = 30
      Width = 96
      Height = 42
      Align = alLeft
      Alignment = taCenter
      AutoSize = False
      Caption = #24744#21363#23558#19979#32447
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
    end
  end
  object Timer1: TTimer
    OnTimer = Timer1Timer
    Left = 256
    Top = 8
  end
  object Timer3: TTimer
    Enabled = False
    OnTimer = Timer3Timer
    Left = 296
    Top = 24
  end
end
