object Form1: TForm1
  Left = 308
  Top = 90
  Width = 1025
  Height = 508
  Caption = #29983#20135#25104#36864'/'#39046#21333
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 16
  object RzPanel1: TRzPanel
    Left = 0
    Top = 0
    Width = 1017
    Height = 49
    Align = alTop
    BorderOuter = fsNone
    BorderColor = clWhite
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Caption = #21414#38376#30591#21644#30005#23376#26377#38480#20844#21496
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -29
    Font.Name = #23435#20307
    Font.Style = [fsBold]
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentFont = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 0
    ThemeAware = False
    object Label1: TLabel
      Left = 0
      Top = 48
      Width = 1017
      Height = 1
      Align = alBottom
      AutoSize = False
      Color = clBlack
      ParentColor = False
      Transparent = False
    end
  end
  object RzPanel2: TRzPanel
    Left = 0
    Top = 49
    Width = 1017
    Height = 49
    Align = alTop
    BorderOuter = fsNone
    BorderColor = clWhite
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 1
    ThemeAware = False
    DesignSize = (
      1017
      49)
    object Label2: TLabel
      Left = 0
      Top = 48
      Width = 1017
      Height = 1
      Align = alBottom
      AutoSize = False
      Color = clBlack
      ParentColor = False
      Transparent = False
    end
    object Label3: TLabel
      Left = 928
      Top = 0
      Width = 89
      Height = 48
      Cursor = crHandPoint
      Align = alRight
      Alignment = taCenter
      AutoSize = False
      Caption = #20445#23384
      Color = clLime
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMaroon
      Font.Height = -16
      Font.Name = #23435#20307
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = False
      Layout = tlCenter
      OnClick = Label3Click
    end
    object RzPanel4: TRzPanel
      Left = 363
      Top = 4
      Width = 289
      Height = 41
      Anchors = []
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 0
      ThemeAware = False
      object RadioButton1: TRadioButton
        Left = 52
        Top = 12
        Width = 77
        Height = 17
        Caption = #36864#26009#21333
        TabOrder = 0
      end
      object RadioButton2: TRadioButton
        Left = 140
        Top = 12
        Width = 97
        Height = 17
        Caption = #39046#36864#26009#21333
        TabOrder = 1
      end
    end
  end
  object RzPanel3: TRzPanel
    Left = 0
    Top = 98
    Width = 1017
    Height = 23
    Align = alTop
    BorderOuter = fsNone
    BorderColor = clWhite
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 2
    ThemeAware = False
    object Label4: TLabel
      Left = 0
      Top = 22
      Width = 1017
      Height = 1
      Align = alBottom
      AutoSize = False
      Color = clBlack
      ParentColor = False
      Transparent = False
    end
    object RzPanel6: TRzPanel
      Left = 433
      Top = 0
      Width = 136
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #39046'/'#36864#26009#21333#20301
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 0
      ThemeAware = False
      object Label6: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
    object RzPanel7: TRzPanel
      Left = 0
      Top = 0
      Width = 161
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #20973#21333#32534#21495
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 1
      ThemeAware = False
      object Label7: TLabel
        Left = 160
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
    object RzPanel8: TRzPanel
      Left = 161
      Top = 0
      Width = 136
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #21046#20196#21333#21495
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 2
      ThemeAware = False
      object Label8: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
    object RzPanel9: TRzPanel
      Left = 297
      Top = 0
      Width = 136
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #25104#21697#21697#30058
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 3
      ThemeAware = False
      object Label9: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
    object RzPanel10: TRzPanel
      Left = 569
      Top = 0
      Width = 136
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #25910'/'#21457#26009#21333#20301
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 4
      ThemeAware = False
      object Label10: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
    object RzPanel11: TRzPanel
      Left = 705
      Top = 0
      Width = 136
      Height = 22
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Caption = #39046'/'#36864#26009#26085#26399
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 5
      ThemeAware = False
      object Label11: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 22
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
    end
  end
  object RzPanel5: TRzPanel
    Left = 0
    Top = 121
    Width = 1017
    Height = 49
    Align = alTop
    BorderOuter = fsNone
    BorderColor = clWhite
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 3
    ThemeAware = False
    object RzPanel12: TRzPanel
      Left = 0
      Top = 0
      Width = 161
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 0
      ThemeAware = False
      object Label12: TLabel
        Left = 160
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit1: TEdit
        Left = 20
        Top = 12
        Width = 121
        Height = 24
        Color = 16776176
        ReadOnly = True
        TabOrder = 0
      end
    end
    object RzPanel13: TRzPanel
      Left = 161
      Top = 0
      Width = 136
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 1
      ThemeAware = False
      object Label13: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit2: TEdit
        Left = 8
        Top = 12
        Width = 121
        Height = 24
        Color = 16776176
        ReadOnly = True
        TabOrder = 0
      end
    end
    object RzPanel14: TRzPanel
      Left = 297
      Top = 0
      Width = 136
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 2
      ThemeAware = False
      object Label14: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit3: TEdit
        Left = 8
        Top = 12
        Width = 121
        Height = 24
        Color = 16776176
        ReadOnly = True
        TabOrder = 0
      end
    end
    object RzPanel15: TRzPanel
      Left = 433
      Top = 0
      Width = 136
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 3
      ThemeAware = False
      object Label15: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit4: TEdit
        Left = 8
        Top = 12
        Width = 121
        Height = 24
        TabOrder = 0
      end
    end
    object RzPanel16: TRzPanel
      Left = 569
      Top = 0
      Width = 136
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 4
      ThemeAware = False
      object Label16: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit5: TEdit
        Left = 8
        Top = 12
        Width = 121
        Height = 24
        TabOrder = 0
      end
    end
    object RzPanel17: TRzPanel
      Left = 705
      Top = 0
      Width = 136
      Height = 49
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 5
      ThemeAware = False
      object Label17: TLabel
        Left = 135
        Top = 0
        Width = 1
        Height = 49
        Align = alRight
        AutoSize = False
        Color = clBlack
        ParentColor = False
        Transparent = False
      end
      object Edit6: TEdit
        Left = 8
        Top = 12
        Width = 121
        Height = 24
        Color = 16776176
        ReadOnly = True
        TabOrder = 0
      end
    end
  end
  object DBGridEh1: TDBGridEh
    Left = 0
    Top = 170
    Width = 1017
    Height = 82
    FixGridlinecolor = clWhite
    Gridlinecolor = clWhite
    FooterDisplayStyle = False
    CurrencyStyle.CurrencyFont.Charset = DEFAULT_CHARSET
    CurrencyStyle.CurrencyFont.Color = clWindowText
    CurrencyStyle.CurrencyFont.Height = -11
    CurrencyStyle.CurrencyFont.Name = 'MS Sans Serif'
    CurrencyStyle.CurrencyFont.Style = []
    CurrencyStyle.CurrencySymbol = #65509
    CurrencyStyle.CompartColor = clSilver
    CurrencyStyle.KilobitColor = clGreen
    CurrencyStyle.RadixColor = clRed
    CurrencyStyle.ShowMinus = True
    CurrencyStyle.ShowZero = False
    CurrencyStyle.MinusColor = clRed
    CurrencyStyle.Layout = tlCenter
    CurrencyStyle.HeadFont.Charset = DEFAULT_CHARSET
    CurrencyStyle.HeadFont.Color = clWindowText
    CurrencyStyle.HeadFont.Height = -11
    CurrencyStyle.HeadFont.Name = #26999#20307'_GB2312'
    CurrencyStyle.HeadFont.Style = []
    Align = alClient
    RowColor1 = 16774625
    RowColor2 = clWhite
    ShowBmp = False
    UseMenu = True
    Ctl3D = False
    DataSource = DataSource1
    FixedColor = clSkyBlue
    Flat = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = #23435#20307
    Font.Style = []
    FooterColor = clWhite
    FooterFont.Charset = DEFAULT_CHARSET
    FooterFont.Color = clWindowText
    FooterFont.Height = -11
    FooterFont.Name = 'MS Sans Serif'
    FooterFont.Style = []
    FrozenCols = 1
    ParentCtl3D = False
    ParentFont = False
    TabOrder = 4
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -16
    TitleFont.Name = 'MS Sans Serif'
    TitleFont.Style = []
    TitleLines = 1
    UseMultiTitle = True
    Columns = <
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'MatlCode'
        Footers = <>
        ReadOnly = True
        Title.Caption = #30591#21644#26009#21495
        Width = 96
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'UNIT'
        Footers = <>
        Title.Caption = #21333#20301
        Width = 85
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'QTY'
        Footers = <>
        Title.Caption = #25968#37327
        Width = 95
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'SUP'
        Footers = <>
        ReadOnly = True
        Title.Caption = #20379#24212#21830
        Width = 125
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'reason1'
        Footers = <>
        Title.Caption = #39046#26009#21407#22240
        Width = 80
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'reason2'
        Footers = <>
        Title.Caption = #36864#26009#21407#22240
        Width = 68
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'memo'
        Footers = <>
        Title.Caption = #19981#33391#25551#36848
        Width = 273
      end
      item
        IsCurrency = False
        DisplayNullIfZero = False
        EditButtons = <>
        FieldName = 'AutoLot'
        Footers = <>
        Visible = False
      end>
  end
  object RzPanel18: TRzPanel
    Left = 0
    Top = 252
    Width = 1017
    Height = 222
    Cursor = crHandPoint
    Align = alBottom
    BorderOuter = fsNone
    BorderColor = clWhite
    BorderHighlight = clWhite
    BorderShadow = clWhite
    Color = clWhite
    Ctl3D = True
    FlatColor = clWhite
    FlatColorAdjustment = 100
    GradientColorStop = clWhite
    GridColor = clWhite
    GridStyle = gsSolidLines
    GridXSize = 1
    GridYSize = 1
    ParentCtl3D = False
    ParentShowHint = False
    ShowHint = False
    TabOrder = 5
    ThemeAware = False
    object RzPanel20: TRzPanel
      Left = 0
      Top = 0
      Width = 222
      Height = 222
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 0
      ThemeAware = False
      object Label23: TLabel
        Left = 21
        Top = 18
        Width = 16
        Height = 64
        Caption = #39046#26009#21407#22240
        WordWrap = True
      end
      object ListBox1: TListBox
        Left = 56
        Top = 0
        Width = 166
        Height = 222
        Align = alRight
        ItemHeight = 16
        TabOrder = 0
      end
    end
    object RzPanel22: TRzPanel
      Left = 222
      Top = 0
      Width = 222
      Height = 222
      Align = alLeft
      BorderOuter = fsNone
      BorderColor = clWhite
      BorderHighlight = clWhite
      BorderShadow = clWhite
      Color = clWhite
      Ctl3D = True
      FlatColor = clWhite
      FlatColorAdjustment = 100
      GradientColorStop = clWhite
      GridColor = clWhite
      GridStyle = gsSolidLines
      GridXSize = 1
      GridYSize = 1
      ParentCtl3D = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 1
      ThemeAware = False
      object Label25: TLabel
        Left = 21
        Top = 18
        Width = 16
        Height = 64
        Caption = #36864#26009#21407#22240
        WordWrap = True
      end
      object ListBox2: TListBox
        Left = 56
        Top = 0
        Width = 166
        Height = 222
        Align = alRight
        ItemHeight = 16
        TabOrder = 0
      end
    end
  end
  object Timer1: TTimer
    Interval = 100
    OnTimer = Timer1Timer
    Left = 64
    Top = 232
  end
  object ClientDataSet1: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'DS_getdata'
    RemoteServer = FDM.SC
    Left = 240
    Top = 244
  end
  object DataSource1: TDataSource
    DataSet = ClientDataSet1
    Left = 277
    Top = 245
  end
  object ClientDataSet2: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'DS_getdata'
    RemoteServer = FDM.SC
    Left = 240
    Top = 292
  end
  object ClientDataSet10: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'DS_getdata'
    RemoteServer = FDM.SC
    Left = 296
    Top = 292
  end
  object Timer2: TTimer
    Interval = 100
    OnTimer = Timer2Timer
    Left = 64
    Top = 280
  end
end
